routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [\App\Http\Controllers\AppController::class, 'dashboard'])->name('dashboard');

Route::resources([
    "cases" => \App\Http\Controllers\GdprCaseController::class,
    "requests" => \App\Http\Controllers\GdprRequestController::class,
    "complaints" => \App\Http\Controllers\ComplaintController::class,
]);

resources/views/pages/cases/create.blade.php
@extends('app')

@section('title')
    Cases / New Case
@endsection

@push('content')
    <form action="{{ route('cases.store') }}" method="POST" name="caseCreate" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-4 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Company Informations</h4>
                        <div class="form-group">
                            <label for="company_name">Name <span class="text-muted">(required)</span> :</label>
                            <input type="text" class="form-control" placeholder="Evil" aria-label="Name" required
                                   id="company_name" name="company_name">
                        </div>
                        <div class="form-group">
                            <label for="company_email">DPO E-Mail <span class="text-muted">(required)</span> :</label>
                            <input type="email" class="form-control" placeholder="privacy@evil.com" aria-label="E-Mail"
                                   required id="company_email" name="company_email">
                        </div>
                        <div class="form-group">
                            <label for="company_website">Domain Name <span class="text-muted">(required)</span>
                                :</label>
                            <input type="text" class="form-control" placeholder="evil.com" aria-label="URL"
                                   id="company_website" name="company_website" required>
                        </div>
                        <div class="form-group">
                            <label for="company_logo">Logo :</label>
                            <input type="file" class="form-control" id="company_logo" name="company_logo">
                        </div>

                        <div class="form-group">
                            <label for="parameters">Additional Parameters :</label>
                            <textarea name="company_parameters" id="company_parameters" rows="3" class="form-control">phone,111 222 333</textarea>
                            <p class="text-sm text-muted">One pair of (key,value) per row.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Case Informations</h4>
                        <div class="form-group">
                            <label for="object">Object <span class="text-muted">(required)</span> :</label>
                            <input type="text" class="form-control" placeholder="Commercial e-mail received" aria-label="Object"
                                   id="object" name="object" required>
                        </div>
                        <div class="form-group">
                            <label for="proof">Proof <span class="text-muted">(required)</span> :</label>
                            <input type="file" class="form-control" name="proof" id="proof" required/>
                        </div>
                        <div class="form-group">
                            <label for="notes">Notes :</label>
                            <textarea class="form-control" name="notes" id="notes" rows="10" placeholder="Received on john.doe@email.com..."></textarea>
                            <small class="text-muted">Supports Markdown</small>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create case" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endpush

@push('scripts')
    <script>
        $('#company_email').on( "focusout", function() {
           let domain = $(this).val().split('@')[1];
           $('#company_website').val(domain);
        });
    </script>
@endpush

resources/views/pages/cases/edit.blade.php
@extends('app')

@section('title')
    Cases / Edit Case #{{ $case->id }} - {{ $case->company->name }}
@endsection

@push('content')
    <form action="{{ route('cases.update', ['case' => $case->id]) }}" method="POST" name="caseEdit">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Case Informations</h4>
                        <div class="form-group">
                            <label for="object">Object <span class="text-muted">(required)</span> :</label>
                            <input type="text" class="form-control" placeholder="Commercial e-mail received" aria-label="Object"
                                   id="object" name="object" required value="{{ $case->object }}">
                        </div>
                        <div class="form-group">
                            <label for="notes">Notes :</label>
                            <textarea class="form-control" name="notes" id="notes" rows="10" placeholder="Received on john.doe@email.com...">{{ $case->notes }}</textarea>
                            <small class="text-muted">Supports Markdown</small>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Edit case" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endpush

@push('scripts')
    <script>
        $('#company_email').on( "focusout", function() {
           let domain = $(this).val().split('@')[1];
           $('#company_website').val(domain);
        });
    </script>
@endpush

resources/views/pages/cases/index.blade.php
@extends('app')

@section('title')
    Cases
@endsection

@push('buttons')
    <a href="{{ route('cases.create') }}" class="btn btn-primary" title="Create new case">New case</a>
@endpush

@push('content')
    <div class="row">
        @if($totalCases === 0)
            <p>This is very empty. You should create a new case to begin.</p>
        @endif

        @if(count($emptyCases) > 0)
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">New cases</h4>
                    <table class="table table-hover" aria-label="New cases">
                        <thead>
                        <tr>
                            <th>Company</th>
                            <th>Object</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($emptyCases as $case)
                            <tr>
                                <td>
                                    <x-company-preview :company="$case->company"/>
                                </td>
                                <td>{{ $case->object }}</td>
                                <td>
                                    <a href="{{ route('cases.show', $case) }}" class="btn btn-sm btn-outline-primary"><span class="material-icons">visibility</span></a>
                                    <a href="{{ route('cases.edit', $case) }}" class="btn btn-sm btn-outline-info"><span class="material-icons">edit</span></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @endif
        @if(count($runningCases) > 0)
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Running cases</h4>
                </div>
            </div>
        </div>
        @endif
        @if(count($expiredCases) > 0)
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">With expired requests</h4>
                </div>
            </div>
        </div>
        @endif
            @if(count($otherCases) > 0)
                <div class="col-6 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Other</h4>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Company</th>
                                        <th>Object</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($otherCases as $case)
                                    <tr>
                                        <td><x-company-preview :company="$case->company"/></td>
                                        <td>{{ $case->object }}</td>
                                        <td>
                                            <a href="{{ route('cases.show', $case) }}" class="btn btn-sm btn-outline-primary"><span class="material-icons">visibility</span></a>
                                            <a href="{{ route('cases.edit', $case) }}" class="btn btn-sm btn-outline-info"><span class="material-icons">edit</span></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @endif
    </div>
@endpush

resources/views/pages/cases/show.blade.php
@extends('app')

@section('title')
    Cases / Case #{{ $case->id }} - {{ $case->company->name }}
@endsection

@push('buttons')
    <a href="{{ route('cases.edit', ['case' => $case->id]) }}" class="btn btn-sm btn-info" title="Edit this case"><span class="material-icons">edit</span></a>
    <a href="{{ route('requests.create', ['case' => $case->id]) }}" class="btn btn-primary" title="Create new case">New GDPR Request</a>
    <a href="{{ route('complaints.create', ['case' => $case->id]) }}" class="btn btn-info" title="Create new complaint">New APD Complaint</a>
@endpush

@push('content')
    <div class="row">
        <div class="col-4 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <x-company-preview :company="$case->company"/>

                    <ul class="mt-3">
                        <li><b>Website :</b> {{ $case->company->website }}</li>
                        @foreach($case->company->parameters as $key => $value)
                            <li><b>{{ ucfirst($key) }} :</b> {{ $value }}</li>
                        @endforeach
                    </ul>

                    <p class="mt-3"><b>Object :</b> {{ $case->object }}</p>

                    <img src="{{ asset("storage/" . $case->proof->path) }}" alt="Proof" class="img-fluid" style="max-height: 250px">
                </div>
            </div>
        </div>
        <div class="col-4 grid-margin stretch-card" style="max-height: 70vh; overflow-y: auto;">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Notes</h4>
                    {!! $case->notesFormatted !!}
                </div>
            </div>
        </div>
        <div class="col-4 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Timeline</h4>
                    <x-timeline :transitions="$transitions"/>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Requests</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Object</th>
                                <th>State</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($case->gdprRequests as $request)
                            <tr>
                                <td title="{{ $request->objectsAsString }}">{{ \Illuminate\Support\Str::limit($request->objectsAsString, 50) }}</td>
                                <td><x-state-badge :state="$request->state"/></td>
                                <td>
                                    <a href="{{ route('requests.show', $request) }}" class="btn btn-sm btn-outline-primary"><span class="material-icons">visibility</span></a>
                                    <a href="{{ route('requests.edit', $request) }}" class="btn btn-sm btn-outline-info"><span class="material-icons">edit</span></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Complaints</h4>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Object</th>
                            <th>State</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($case->complaints as $complaint)
                            <tr>
                                <td>{{ $complaint->object }}</td>
                                <td><x-state-badge :state="$complaint->state"/></td>
                                <td>
                                    <a href="{{ route('complaints.show', $request) }}" class="btn btn-sm btn-outline-primary"><span class="material-icons">visibility</span></a>
                                    <a href="{{ route('complaints.edit', $request) }}" class="btn btn-sm btn-outline-info"><span class="material-icons">edit</span></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endpush