routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [\App\Http\Controllers\AppController::class, 'dashboard'])->name('dashboard');

Route::resources([
    "cases" => \App\Http\Controllers\GdprCaseController::class,
    "requests" => \App\Http\Controllers\GdprRequestController::class,
    "complaints" => \App\Http\Controllers\ComplaintController::class,
]);

resources/views/partials/footer.blade.php
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
        <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Version {{ config('app.version') }} - {{ config('app.name') }}</span>
        <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"><a href="#">Gitlab</a></span>
    </div>
</footer>

resources/views/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('dashboard') }}">
                <span class="menu-title">{{ __("Dashboard") }}</span>
                <i class="material-icons menu-icon">dashboard</i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('cases.index') }}">
                <span class="menu-title">{{ __("GDPR Cases") }}</span>
                <i class="material-icons menu-icon">folder</i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('requests.index') }}">
                <span class="menu-title">{{ __("GDPR Requests") }}</span>
                <i class="material-icons menu-icon">help</i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('complaints.index') }}">
                <span class="menu-title">{{ __("DPA Complaints") }}</span>
                <i class="material-icons menu-icon">gpp_maybe</i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <span class="menu-title">{{ __("Templates") }}</span>
                <i class="material-icons menu-icon">description</i>
            </a>
        </li>
    </ul>
</nav>

resources/views/partials/topbar.blade.php
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <img src="/assets/images/logo.png" alt="Logo {{ config('app.name') }}" class="img-fluid w-25"/>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="material-icons">menu</span>
        </button>
        <div class="search-field d-none d-lg-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search for cases">
                </div>
            </form>
        </div>
    </div>
</nav>